### ISSUE TITLE
Script crashes after joing a meet

### ISSUE THREAD

**Issue by shakeabi** [TobiasPankner/Teams-Auto-Joiner#16]
**Describe the bug**
Once the script joins a meet, in the next iteration of updating channels, it crashes.
Note: the spawned chrome doesn't close as it would do when you manually close it.

```
Traceback (most recent call last):
  File "auto_joiner.py", line 427, in <module>
    main()
  File "auto_joiner.py", line 415, in main
    team.update_meetings()
  File "auto_joiner.py", line 99, in update_meetings
    channels = self.expand_channels()
  File "auto_joiner.py", line 63, in expand_channels
    elem = self.elem.find_element_by_css_selector("div.channels")
  File "/home/shake/delta/playground/Teams-Auto-Joiner/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/shake/delta/playground/Teams-Auto-Joiner/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "/home/shake/delta/playground/Teams-Auto-Joiner/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/shake/delta/playground/Teams-Auto-Joiner/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/shake/delta/playground/Teams-Auto-Joiner/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=83.0.4103.116)
```

**Expected behavior**
Shouldnt Crash

**Configuration file**
```
{
  "email": "",
  "password": "",

  "start_automatically": false,
  "organisation_num": 1,
  "random_delay": false,
  "check_interval": 60,

  "auto_leave_after_min": -1,
  "leave_if_last": true,

  "headless": false,
  "mute_audio": false,
  "chrome_type": "google-chrome",

  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
    {
      "team_name": "Blacklist whole team",
      "channel_names": []
    }
  ]
}
```

**Desktop (please complete the following information):**
 - OS: Manjaro 20.1
 - Browser: Chrome
 - Version: 83.0.4103

**Comment by shakeabi** [comment]
I tried twice, and it happened both times..

**Comment by pWoLiAn** [comment]
I am also experiencing the same issue.This happens when the browser asks me for microphone/camera permissions.

**Comment by H4D53** [comment]
i have the same problem , here is my error code
`[09:41:08] Updating channels
Traceback (most recent call last):
  File "C:\Users\hmcha\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 64, in expand_channels
    elem = self.elem.find_element_by_css_selector("div.channels")
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.channels"}
  (Session info: chrome=85.0.4183.121)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hmcha\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 442, in <module>
    main()
  File "C:\Users\hmcha\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 415, in main
    team.update_meetings()
  File "C:\Users\hmcha\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 100, in update_meetings
    channels = self.expand_channels()
  File "C:\Users\hmcha\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 68, in expand_channels
    elem = self.elem.find_element_by_css_selector("div.channels")
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=85.0.4183.121)`

**Comment by TobiasPankner** [comment]
With the newest version (big update) this is hopefully fixed, if not please open a new issue.

**Comment by dotrachit** [comment]
@TobiasPankner I'm facing the same issue.

## log
```
[12:08:14] Looking for new meetings
Traceback (most recent call last):
  File "auto_joiner.py", line 54, in expand_channels
    self.get_elem().find_element_by_css_selector("div.channels")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.channels"}
  (Session info: chrome=85.0.4183.121)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto_joiner.py", line 603, in <module>
    main()
  File "auto_joiner.py", line 550, in main
    teams = get_all_teams()
  File "auto_joiner.py", line 272, in get_all_teams
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "auto_joiner.py", line 272, in <listcomp>
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "auto_joiner.py", line 36, in __init__
    self.get_channels()
  File "auto_joiner.py", line 63, in get_channels
    self.expand_channels()
  File "auto_joiner.py", line 57, in expand_channels
    self.get_elem().click()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div sv-element="{ containment: '.ts-channel-list', revert: 0, delay: 400, hideOriginalOnDrag: false }" data-tid="team-Robotronics 2020-li" class="team">...</div> is not clickable at point (208, 917). Other element would receive the click: <div class="team-operations-container app-left-rail-width" ng-if="!clc.blockTeamOperations &amp;&amp; !clc.filterInputOn" data-tid="teamOperationsContainer">...</div>
  (Session info: chrome=85.0.4183.121)
```

**Comment by TobiasPankner** [comment]
A video would be extremely helpful for this issue. If you could provide one (showing chrome and cmd) that would be great.  
You can also send it to me by email.
