### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by hanselsaji** [TobiasPankner/Teams-Auto-Joiner#161]
D:\Teams-Auto-Joiner-master>python auto_joiner.py
ERROR: The system was unable to find the specified registry key or value.
Traceback (most recent call last):
  File "D:\Teams-Auto-Joiner-master\auto_joiner.py", line 770, in <module>
    main()
  File "D:\Teams-Auto-Joiner-master\auto_joiner.py", line 618, in main
    init_browser()
  File "D:\Teams-Auto-Joiner-master\auto_joiner.py", line 180, in init_browser
    browser = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "C:\Users\hanse\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\chrome.py", line 23, in __init__
    self.driver = ChromeDriver(name=name,
  File "C:\Users\hanse\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\driver.py", line 54, in __init__
    self.browser_version = chrome_version(chrome_type)
  File "C:\Users\hanse\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\utils.py", line 142, in chrome_version
    raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version

**Comment by TobiasPankner** [comment]
It looks like you don't have Google Chrome installed.

**Comment by hanselsaji** [comment]
I have both Chrome and Edge
Both have the same error!

**Comment by TobiasPankner** [comment]
Please try the solution mentioned here:  
https://SergeyPirogov/webdriver_manager/issues/205#issuecomment-926514305

**Comment by hanselsaji** [comment]
> Please try the solution mentioned here: [SergeyPirogov/webdriver_manager#205 (comment)](https://github.com/SergeyPirogov/webdriver_manager/issues/205#issuecomment-926514305)

Nope bro, Same!


ERROR: The system was unable to find the specified registry key or value.
Traceback (most recent call last):
  File "D:\Teams-Auto-Joiner-master\auto_joiner.py\", line 770, in <module>
    main()
  File "D:\Teams-Auto-Joiner-master\auto_joiner.py\", line 618, in main
    init_browser()
  File "D:\Teams-Auto-Joiner-master\auto_joiner.py\", line 180, in init_browser
    browser = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "C:\Users\hanse\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\chrome.py", line 23, in __init__
    self.driver = ChromeDriver(name=name,
  File "C:\Users\hanse\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\driver.py", line 54, in __init__
    self.browser_version = chrome_version(chrome_type)
  File "C:\Users\hanse\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\utils.py", line 142, in chrome_version
    raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version

**Comment by TobiasPankner** [comment]
Okay one more thing you could try. 
Download chromedriver for your version of the browser.  
Then replace the WebdriverManager part in line [180](https://github.com/TobiasPankner/Teams-Auto-Joiner/blob/master/auto_joiner.py#L180) with the path to the downloaded .exe

**Comment by hanselsaji** [comment]
Anyway Thanks bro
I got the error 
it was because I was using Chrome beta
but don't know what's the problem with edge...

**Comment by TobiasPankner** [comment]
Glad that it works now!  
Did you change the value in the config correctly for edge?

**Comment by hanselsaji** [comment]
> Glad that it works now! Did you change the value in the config correctly for edge?

Yes, I have given ms-edge but it open chrome..

**Comment by TobiasPankner** [comment]
It's `msedge` without the hyphen

**Comment by hanselsaji** [comment]
Oh ok 
Thank You Very Much..
