### ISSUE TITLE
Stops on its own

### ISSUE THREAD

**Issue by skyshines** [TobiasPankner/Teams-Auto-Joiner#164]
**Describe the bug**
Script stops on its own

**Screenshots**
[13:58:50] Looking for new meetings
Traceback (most recent call last):
  File "auto_joiner.py", line 58, in expand_channels
    self.get_elem().find_element_by_css_selector("div.channels")
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.channels"}
  (Session info: chrome=97.0.4692.71)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto_joiner.py", line 770, in <module>
    main()
  File "auto_joiner.py", line 713, in main
    teams = get_all_teams()
  File "auto_joiner.py", line 311, in get_all_teams
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "auto_joiner.py", line 311, in <listcomp>
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "auto_joiner.py", line 40, in __init__
    self.get_channels()
  File "auto_joiner.py", line 67, in get_channels
    self.expand_channels()
  File "auto_joiner.py", line 62, in expand_channels
    self.get_elem().find_element_by_css_selector("div.channels")
  File "auto_joiner.py", line 53, in get_elem
    team_elem = team_header.find_element_by_xpath("..")
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 351, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/sky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=97.0.4692.71)

**Desktop :**
 - Linux
 - Chrome(original from official site)
 - Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by skyshines** [comment]
@TobiasPankner pls help

**Comment by TobiasPankner** [comment]
Sorry for the late reply, have you tried running it in headful mode to see what's happening?

**Comment by skyshines** [comment]
yes i run it in maximized mode, never ran it in minimize or headless mode

**Comment by TobiasPankner** [comment]
Okay, a video would be helpful if because I cannot reproduce the issue

**Comment by skyshines** [comment]
It closes on its own
since i have a discord webhook url attached
it gives me a message browser closed thank you
i will try giving you a video

**Comment by AP-XD** [comment]
How to track keypress in terminal?
With that we can resume search on keypress in terminal in case in gets stuck

**Comment by AP-XD** [comment]
> Okay, a video would be helpful if because I cannot reproduce the issue

![image](https://user-images.githubusercontent.com/63340491/150299430-76b03e26-ac56-407e-9c9d-0f4a02d34d4e.png)
Meeting got ended by host in the red part and then it keeps spamming that forever.

**Comment by TobiasPankner** [comment]
> How to track keypress in terminal?
> With that we can resume search on keypress in terminal in case in gets stuck
> 

Thats not really what I have in mimd with this bot though. You should be able to leave the computer and let it do it's thing without input. Thats the whole point

**Comment by TobiasPankner** [comment]
> > Okay, a video would be helpful if because I cannot reproduce the issue
> 
> ![image](https://user-images.githubusercontent.com/63340491/150299430-76b03e26-ac56-407e-9c9d-0f4a02d34d4e.png)
> Meeting got ended by host in the red part and then it keeps spamming that forever.
> 

I don't see how the picture is related to this issue. Please create a new issue

**Comment by skyshines** [comment]
@AP-XD i just found a fix, not a code
the moment it checks for a new meeting
scroll up and down a bit
it will open the meet as it is supposed to

why this works for me
i want to to store the max members in a meet
so that i can ignore it and rest it can handle itself

**Comment by TobiasPankner** [comment]
Very weird, can you post a screenshot of chrome to help me fix this issue?
