### ISSUE TITLE
Crashes after an hour

### ISSUE THREAD

**Issue by keshavbantu** [TobiasPankner/Teams-Auto-Joiner#19]
**The bug**
Runs perfectly, but after an hour and a half (estimate), and joining 2 classes. This happens in the middle of the 2nd class.
(i have renamed the file for easier run). 
Do you know why this happens? I feel like its some power saving sorta stuff on the driver itself?

``
Traceback (most recent call last):

  File "join.py", line 63, in expand_channels
    elem = self.elem.find_element_by_css_selector("div.channels")
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.channels"}
  (Session info: headless chrome=84.0.4147.125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "join.py", line 429, in <module>
    main()
  File "join.py", line 417, in main
    team.update_meetings()
  File "join.py", line 99, in update_meetings
    channels = self.expand_channels()
  File "join.py", line 66, in expand_channels
    self.elem.click()
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/bantu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div sv-element="{ containment: '.ts-channel-list', revert: 0, delay: 400, hideOriginalOnDrag: false }" data-tid="team-UE18ME311 (5TH ELECTIVE-1) Turbomachines-li" class="team">...</div> is not clickable at point (208, 542). Other element would receive the click: <div class="team-operations-container app-left-rail-width" ng-if="!clc.blockTeamOperations &amp;&amp; !clc.filterInputOn" data-tid="teamOperationsContainer">...</div>
  (Session info: headless chrome=84.0.4147.125)
``

**Comment by TobiasPankner** [comment]
Could it be that the windows is somehow resized or that something is in front of the window?

**Comment by keshavbantu** [comment]
I doubt it, its running headless. So the only things open are my terminal running the script and vlc playing movies.
What you mean is, there is some process running that is interfering with the script?

Ill look into it and report back. Ill just run the terminal and give it a try.

**Comment by harshdonga** [comment]
Just run in headless mode! Solves it

**Comment by TobiasPankner** [comment]
I just pushed a big update, now this hopefully fixed. If not, please open a new issue
