### ISSUE TITLE
Hidden Groups Crash

### ISSUE THREAD

**Issue by Dartypier** [TobiasPankner/Teams-Auto-Joiner#2]
Hi, the script works fine without hidden teams, if some teams are hidden the script will crash (so at the moment the fix consists in making those teams visible or deleting them).

Output:
```[WDM] - Cache is valid for [04/06/2020]
[WDM] - Looking for [chromedriver 83.0.4103.39 linux64] driver in cache 
[WDM] - Driver found in cache [/home/user/.wdm/drivers/chromedriver/83.0.4103.39/linux64/chromedriver]
Waiting for correct page...
Traceback (most recent call last):
  File "auto_joiner.py", line 335, in <module>
    main()
  File "auto_joiner.py", line 295, in main
    team.init_channels()
  File "auto_joiner.py", line 73, in init_channels
    channel_elems = channels_elem.find_elements_by_css_selector("ul>ng-include>li")
AttributeError: 'NoneType' object has no attribute 'find_elements_by_css_selector'
```

**Comment by TobiasPankner** [comment]
Thanks for reporting. Should be fixed with the commit 128d025a7ea3ae3108f61efc12eac265162b5c30.
