### ISSUE TITLE
Keeps crashing again and again.

### ISSUE THREAD

**Issue by Sam-Hack-King** [TobiasPankner/Teams-Auto-Joiner#49]
### The python Script keeps crashing with the following Errors:
`
Traceback (most recent call last):
  File "auto_joiner.py", line 54, in expand_channels
    self.get_elem().find_element_by_css_selector("div.channels")
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 659, in find_element
    {"using": by, "value": value})['value']
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.channels"}
  (Session info: chrome=86.0.4240.183)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto_joiner.py", line 636, in <module>
    main()
  File "auto_joiner.py", line 582, in main
    teams = get_all_teams()
  File "auto_joiner.py", line 283, in get_all_teams
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "auto_joiner.py", line 283, in <listcomp>
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "auto_joiner.py", line 36, in __init__
    self.get_channels()
  File "auto_joiner.py", line 63, in get_channels
    self.expand_channels()
  File "auto_joiner.py", line 57, in expand_channels
    self.get_elem().click()
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\sampurn\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div sv-element="{ containment: '.ts-channel-list', revert: 0, delay: 400, hideOriginalOnDrag: false }" data-tid="team-CSPC32 IP-li" class="team">...</div> is not clickable at point (208, 706). Other element would receive the click: <div class="team-operations-container app-left-rail-width" ng-if="!clc.blockTeamOperations &amp;&amp; !clc.filterInputOn" data-tid="teamOperationsContainer">...</div>
  (Session info: chrome=86.0.4240.183)`

**Comment by TobiasPankner** [comment]
What is shown in the browser window at the time of error?

**Comment by Sam-Hack-King** [comment]
Browser Window automatically shuts down without showing any errors or anything. 
Moreover, the headless mode is also not working. It is showing a long list of errors and the command prompt then freezes.

**Comment by Wolfyg11** [comment]
I had the same error. It joined a meeting and continued to look for new meetings which it did and somewhere in the middle of it crashed.
[WDM] - Cache is valid for [16/11/2020]
[WDM] - Looking for [chromedriver 86.0.4240.22 win32] driver in cache
[WDM] - Driver found in cache [C:\Users\farka\.wdm\drivers\chromedriver\86.0.4240.22\win32\chromedriver.exe]

DevTools listening on ws://127.0.0.1:63446/devtools/browser/0208db36-d5bb-4fc4-8cfa-f72b3c43e287
Resized window width
Resized window height
Found page, do not click anything on the webpage from now on.

20/21. Informatika 12.C BM
        General
20/21. ének 12.C ZE
        General
20/21 Angol 12 AC ny2
        General
20/21. TÖRTÉNELEM 12C NI
        General
20/21 Német 12.AC HFE
        General
20/21. Média 12. évfolyam - BCs
        General
20/21. ÉLETVITEL 12C NI
        General
20/21. Etika 12. évfolyam - BCs
        General
20/21. Magyar 12.C SzG
        General
20/21. Matek 12.C PR
        General
20/21. BIOLÓGIA 12C NI
        General
20/21. testnevelés DSK NyB
        General
20/21 OSZTÁLYFŐNÖKI 12c
        General [MEETING]
20/21. testnevelés 12.C NyB
        General

[08:05:14] Looking for new meetings
Found meetings:
        20/21 OSZTÁLYFŐNÖKI 12c -> General 1605202867 [Channel]
Video off
Joined meeting: 20/21 OSZTÁLYFŐNÖKI 12c -> General

[08:05:52] Looking for new meetings
Traceback (most recent call last):
  File "C:\Users\farka\Desktop\Teams_Joiner\Teams-Auto-Joiner-master\auto_joiner.py", line 54, in expand_channels
    self.get_elem().find_element_by_css_selector("div.channels")
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.channels"}
  (Session info: chrome=86.0.4240.198)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\farka\Desktop\Teams_Joiner\Teams-Auto-Joiner-master\auto_joiner.py", line 636, in <module>
    main()
  File "C:\Users\farka\Desktop\Teams_Joiner\Teams-Auto-Joiner-master\auto_joiner.py", line 582, in main
    teams = get_all_teams()
  File "C:\Users\farka\Desktop\Teams_Joiner\Teams-Auto-Joiner-master\auto_joiner.py", line 283, in get_all_teams
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "C:\Users\farka\Desktop\Teams_Joiner\Teams-Auto-Joiner-master\auto_joiner.py", line 283, in <listcomp>
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "C:\Users\farka\Desktop\Teams_Joiner\Teams-Auto-Joiner-master\auto_joiner.py", line 36, in __init__
    self.get_channels()
  File "C:\Users\farka\Desktop\Teams_Joiner\Teams-Auto-Joiner-master\auto_joiner.py", line 63, in get_channels
    self.expand_channels()
  File "C:\Users\farka\Desktop\Teams_Joiner\Teams-Auto-Joiner-master\auto_joiner.py", line 57, in expand_channels
    self.get_elem().click()
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\farka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div sv-element="{ containment: '.ts-channel-list', revert: 0, delay: 400, hideOriginalOnDrag: false }" data-tid="team-20/21. Matek 12.C PR-li" class="team">...</div> is not clickable at point (208, 705). Other element would receive the click: <div class="team-operations-container app-left-rail-width" ng-if="!clc.blockTeamOperations &amp;&amp; !clc.filterInputOn" data-tid="teamOperationsContainer">...</div>
  (Session info: chrome=86.0.4240.198)

**Comment by Joseph-Souaiby** [comment]
Same error. I just posted it. Plz Tobias can you try to fix it cuz it's happening to everyone. It would be greatly appreciated :)
