### ISSUE TITLE
I have trouble with the setup.

### ISSUE THREAD

**Issue by Kaliumnitrit** [TobiasPankner/Teams-Auto-Joiner#51]
Dear TobiasPanker/users,

this is my first time getting in touch with a code. I think I have done everything right, installed all pip req's and have Phyton installed. But apparently he can't find the config.json file, even tho I have everything in one folder. This is my output:

============ RESTART: C:\Users\Leon\Desktop\Teams Bot\auto_joiner.py ===========
Traceback (most recent call last):
  File "C:\Users\Leon\Desktop\Teams Bot\auto_joiner.py", line 620, in <module>
    load_config()
  File "C:\Users\Leon\Desktop\Teams Bot\auto_joiner.py", line 131, in load_config
    with open('config.json') as json_data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

I hope someone can help me because this is a very cool project and I would really like to use it 😃 
Best greetings!

**Comment by Kaliumnitrit** [comment]
I found out that I only have a problem with that file. There is another version of this bot from the user  "Harshalshree" and it worked perfectly fine. Im gonna try my best to get it running, but I don't know where my issue is..

**Comment by TobiasPankner** [comment]
You probably didn't rename the config file. Press rename on the file and delete the example part.

**Comment by Kaliumnitrit** [comment]
Thanks for the fast reply, but I can't get it working. Iv'e tried it for a few hours now and there is still nothing coming out. I will close this issue window now. Good Luck for further projects! 👍

**Comment by TobiasPankner** [comment]
Did you watch the video?
