### ISSUE TITLE
Browser crashes

### ISSUE THREAD

**Issue by saadmustafa12** [TobiasPankner/Teams-Auto-Joiner#55]
**Describe the bug**
[1203/091520.323:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)

**To Reproduce**
1. Everything working fine
2. It joined the meeting Automatically
3. After 15  to 20 mins it crashed and chrome browser closed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.88

**Comment by TobiasPankner** [comment]
I need the full error to know what is happening

**Comment by saadmustafa12** [comment]
> I need the full error to know what is happening

Please can you tell from where i can get error log? 
Because Python window crash immediately after this error occurs..
I currently shared debug file content

**Comment by TobiasPankner** [comment]
Just start the script from cmd, like in the video or Readme file

**Comment by saadmustafa12** [comment]
> Just start the script from cmd, like in the video or Readme file

Ok i am currently running it again and will share error log as it crashes...

**Comment by saadmustafa12** [comment]
> I need the full error to know what is happening

Traceback (most recent call last):
  File "C:\Users\Saad Mustafa\Hacked Folder\Teams-Auto-Joiner-master\auto_joiner.py", line 636, in <module>
    main()
  File "C:\Users\Saad Mustafa\Hacked Folder\Teams-Auto-Joiner-master\auto_joiner.py", line 607, in main
    members = get_meeting_members()
  File "C:\Users\Saad Mustafa\Hacked Folder\Teams-Auto-Joiner-master\auto_joiner.py", line 452, in get_meeting_members
    browser.execute_script("document.getElementById('roster-button').click()")
  File "C:\Users\Tech Feast JBS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\Tech Feast JBS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Tech Feast JBS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'click' of null
  (Session info: chrome=87.0.4280.88)


This is the complete error

**Comment by Kaloyan675** [comment]
I have the same problem and found out that it crashes with the exact same message when i click on the meeting(to expand the mini window of the meeting) I think it has to do something with the hanging up
![teams](https://user-images.githubusercontent.com/75611384/101334578-bb0b9580-3880-11eb-93aa-f9b82091e626.png)
when i click that i get that: [11:39:34] Looking for new meetings
Traceback (most recent call last):
  File "C:\Users\*\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 636, in <module>
    main()
  File "C:\Users\*\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 582, in main
    teams = get_all_teams()
  File "C:\Users\*\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 283, in get_all_teams
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "C:\Users\*\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 283, in <listcomp>
    return [Team(team_names[i], team_ids[i]) for i in range(len(team_elems))]
  File "C:\Users\*\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 36, in __init__
    self.get_channels()
  File "C:\Users\*\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 64, in get_channels
    channels = self.get_elem().find_elements_by_css_selector(".channels > ul > ng-include > li")
  File "C:\Users\*\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 48, in get_elem
    team_header = browser.find_element_by_css_selector(f"h3[id='{self.t_id}'")
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"h3[id='team-19:a46f557065a14804a494b9bb14791fa2@thread.tacv2'"}
  (Session info: chrome=86.0.4240.198)

**Comment by TobiasPankner** [comment]
If you click anything I cannot guarantee it working. You should just let it run and not interact with the window.
If you want to do something with Teams open a new browser window.

**Comment by Kaloyan675** [comment]
Yeah i know but it happens even without me clicking on it. I clicked to try and debug it(find the problem) and found this out thought might help you out with fixing it.

**Comment by TobiasPankner** [comment]
Should be fixed with commit 26b3529
