### ISSUE TITLE
[Solved] "chrome_type": "msedge" Not Working

### ISSUE THREAD

**Issue by WIFIGUN** [TobiasPankner/Teams-Auto-Joiner#56]
**Describe the bug**
Script crashes about webdriver_manager

**Video**
[https://youtu.be/Q3W46-GF6IY](https://youtu.be/Q3W46-GF6IY)

Run auto_joiner.py: py -3 auto_joiner.py
`Traceback (most recent call last):
  File "C:\Users\WONGH\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 636, in <module>
    main()
  File "C:\Users\WONGH\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 504, in main
    init_browser()
  File "C:\Users\WONGH\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 173, in init_browser
    browser = Edge(EdgeChromiumDriverManager().install(), options=chrome_options)
  File "C:\Python\Python39\lib\site-packages\webdriver_manager\microsoft.py", line 45, in install
    return self.download_driver(self.driver)
  File "C:\Python\Python39\lib\site-packages\webdriver_manager\manager.py", line 44, in download_driver
    path = self.__download_and_save_driver_to_cache(driver, driver_version)
  File "C:\Python\Python39\lib\site-packages\webdriver_manager\manager.py", line 32, in __download_and_save_driver_to_cache
    response = download_driver(driver.get_url(driver_version))
  File "C:\Python\Python39\lib\site-packages\webdriver_manager\utils.py", line 58, in download_driver
    log(f"Trying to download new driver from {url}")
  File "C:\Python\Python39\lib\site-packages\webdriver_manager\logger.py", line 12, in log
    level = int(log_level)
ValueError: invalid literal for int() with base 10: 'None'`

**Configuration file**
```
{
  "email": "",
  "password": "",

  "run_at_time": "",

  "meeting_mode": 3,
  "organisation_num" : 1,
  "random_delay": true,
  "check_interval": 20,

  "auto_leave_after_min": -1,
  "leave_if_last": false,

  "headless" : false,
  "mute_audio": true,
  "chrome_type": "msedge",
  
  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
     {
      "team_name": "Blacklist whole team",
      "channel_names": [
      ]
    }
  ],
  "blacklist_meeting_re": ""
}
```

**Desktop**
 -Windows 10 x64
 -MicrosoftEdge=87.0.664.57
 -python=3.9.0

**Additional context**
please update the requirements.txt
```
selenium==3.141.0
webdriver_manager==3.2.2
msedge-selenium-tools==3.141.3
```

**Comment by TobiasPankner** [comment]
Changed requirements.txt in commit 6818f4c
