### ISSUE TITLE
Browser crashing for no reason

### ISSUE THREAD

**Issue by Joseph-Souaiby** [TobiasPankner/Teams-Auto-Joiner#60]
The browser sometimes crashes for no reason. I have no idea when or why that happens. It just happens randomly. I never even clicked on the screen. Never clicked on anything after I executed the code.
This is what appears after it crashes :

Traceback (most recent call last):
  File "C:\Users\PC.CC\Desktop\My Teams-Auto-Joiner\auto_joiner.py", line 642, in <module>
    main()
  File "C:\Users\PC.CC\Desktop\My Teams-Auto-Joiner\auto_joiner.py", line 614, in main
    members = get_meeting_members()
  File "C:\Users\PC.CC\Desktop\My Teams-Auto-Joiner\auto_joiner.py", line 455, in get_meeting_members
    browser.execute_script("document.getElementById('roster-button').click()")
  File "C:\Users\PC.CC\Desktop\My Teams-Auto-Joiner\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\PC.CC\Desktop\My Teams-Auto-Joiner\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC.CC\Desktop\My Teams-Auto-Joiner\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'click' of null
  (Session info: chrome=87.0.4280.88)

**Comment by TobiasPankner** [comment]
The error you mentioned is fixed with commit 26b3529
