### ISSUE TITLE
error with the auto_joiner.py

### ISSUE THREAD

**Issue by nqassim** [TobiasPankner/Teams-Auto-Joiner#87]
Hello, I have made sure to install all the dependencies and my config file seems fine. However, I keep getting these errors when running the python script
`Traceback (most recent call last):
  File "C:\Python38-32\Lib\Teams-Auto-Joiner-master\auto_joiner.py", line 673, in <module>
    load_config()
  File "C:\Python38-32\Lib\Teams-Auto-Joiner-master\auto_joiner.py", line 133, in load_config
    config = json.load(json_data_file)
  File "C:\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 21 (char 151)`

the config seems fine, I followed all the steps
the path is C:\Python38-32\Lib\Teams-Auto-Joiner-master

anyone got a fix ?

**Comment by TobiasPankner** [comment]
The error is with the formatting of the json file. 
Cop the contents and put them into an online json parser, there you will see the issue.
