### ISSUE TITLE
I used the script for months and it suddenly stopped working :(

### ISSUE THREAD

**Issue by dam2452** [TobiasPankner/Teams-Auto-Joiner#90]
The script worked for many months and suddenly it stopped, I suspect that I was reinstalling python because of some updating, I downloaded everything again and even tried the method turn off and on, please help.

Microsoft Windows [Version 10.0.19042.867]
(c) 2020 Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Teams-Auto-Joiner-master>python auto_joiner.py
Traceback (most recent call last):
  File "C:\Teams-Auto-Joiner-master\auto_joiner.py", line 673, in <module>
    load_config()
  File "C:\Teams-Auto-Joiner-master\auto_joiner.py", line 133, in load_config
    config = json.load(json_data_file)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 17 column 3 (char 317)

i see it when i try run it :((

Microsoft Windows [Version 10.0.19042.867]
(c) 2020 Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Teams-Auto-Joiner-master>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium==3.141.0 in c:\users\zodia\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 1)) (3.141.0)
Requirement already satisfied: webdriver_manager==3.2.2 in c:\users\zodia\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 2)) (3.2.2)
Requirement already satisfied: msedge-selenium-tools==3.141.3 in c:\users\zodia\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 3)) (3.141.3)
Requirement already satisfied: urllib3 in c:\users\zodia\appdata\roaming\python\python39\site-packages (from selenium==3.141.0->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: crayons in c:\users\zodia\appdata\roaming\python\python39\site-packages (from webdriver_manager==3.2.2->-r requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: requests in c:\users\zodia\appdata\roaming\python\python39\site-packages (from webdriver_manager==3.2.2->-r requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: configparser in c:\users\zodia\appdata\roaming\python\python39\site-packages (from webdriver_manager==3.2.2->-r requirements.txt (line 2)) (5.0.2)
Requirement already satisfied: colorama in c:\users\zodia\appdata\roaming\python\python39\site-packages (from crayons->webdriver_manager==3.2.2->-r requirements.txt (line 2)) (0.4.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\zodia\appdata\roaming\python\python39\site-packages (from requests->webdriver_manager==3.2.2->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\zodia\appdata\roaming\python\python39\site-packages (from requests->webdriver_manager==3.2.2->-r requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zodia\appdata\roaming\python\python39\site-packages (from requests->webdriver_manager==3.2.2->-r requirements.txt (line 2)) (2020.12.5)

and this when i write this  pip install -r requirements.txt

{
  "email": "",
  "password": "",

  "run_at_time": "",

  "meeting_mode": 1,
  "organisation_num" : 1,
  "random_delay": true,
  "check_interval": 10,

  "join_message": "",

  "auto_leave_after_min": -1,
  "leave_if_last": true,
  "leave_threshold_number": ""
  "leave_threshold_percentage": "",
  "pause_search": false,

  "headless" : false,
  "mute_audio": true,
  "chrome_type": "google-chrome",

  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
     {
      "team_name": "Blacklist whole team",
      "channel_names": [
      ]
    }
  ],
  "blacklist_meeting_re": ""
}

 - Windows 20H2 (19042.867)
 - Google Chrome
 - Wersja 89.0.4389.90 (Oficjalna wersja) (64-bitowa)

**Comment by dam2452** [comment]
I am asking for help quickly because I need it like water.

**Comment by TobiasPankner** [comment]
There is a "," character missing in the config at the leave_treshold_number line.

**Comment by dam2452** [comment]
I added the missing "," and it still doesn't work.

{
  "email": "",
  "password": "",

  "run_at_time": "",

  "meeting_mode": 1,
  "organisation_num" : 1,
  "random_delay": true,
  "check_interval": 10,

  "join_message": "",

  "auto_leave_after_min": -1,
  "leave_if_last": true,
  "leave_threshold_number": "",
  "leave_threshold_percentage": "",
  "pause_search": false,

  "headless" : false,
  "mute_audio": true,
  "chrome_type": "google-chrome",

  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
     {
      "team_name": "Blacklist whole team",
      "channel_names": [
      ]
    }
  ],
  "blacklist_meeting_re": ""
}


Microsoft Windows [Version 10.0.19042.867]
(c) 2020 Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Teams-Auto-Joiner-master>python auto_joiner.py

[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
Traceback (most recent call last):
  File "C:\Teams-Auto-Joiner-master\auto_joiner.py", line 689, in <module>
    main()
  File "C:\Teams-Auto-Joiner-master\auto_joiner.py", line 552, in main
    init_browser()
  File "C:\Teams-Auto-Joiner-master\auto_joiner.py", line 177, in init_browser
    browser = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "C:\Users\zodia\AppData\Roaming\Python\Python39\site-packages\webdriver_manager\chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\zodia\AppData\Roaming\Python\Python39\site-packages\webdriver_manager\manager.py", line 24, in _get_driver_path
    binary_path = self.driver_cache.find_driver(browser_version, driver_name, os_type,
  File "C:\Users\zodia\AppData\Roaming\Python\Python39\site-packages\webdriver_manager\driver_cache.py", line 66, in find_driver
    metadata = self.get_metadata()
  File "C:\Users\zodia\AppData\Roaming\Python\Python39\site-packages\webdriver_manager\driver_cache.py", line 91, in get_metadata
    return json.load(outfile)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by TobiasPankner** [comment]
This seems to be an issue with an external package. Try updating the webdriver-manager package

**Comment by dam2452** [comment]
How to do it?

**Comment by dam2452** [comment]
I am not an advanced Python developer so you have to explain this to me simply and thoroughly.

**Comment by TobiasPankner** [comment]
Run "pip install -r requirements.txt" again.  
If that doesn't work run "pip install webdriver-manager -U".  
If that also doesn't help just try reinstalling python and this bot.

**Comment by dam2452** [comment]
Still not working. first I typed "pip install -r requirements.txt" then "pip install webdriver-manager -U" it still didn't work, that's why I uninstalled python, restarted the computer, then installed and restarted the computer, it still didn't work, so I downloaded the bot again, just entered the email and password for the configuration and deleted . example and then the same as at the beginning.

C:\Users\zodia\OneDrive\Pulpit\Teams-Auto-Joiner-master>python auto_joiner.py


[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
Traceback (most recent call last):
  File "C:\Users\zodia\OneDrive\Pulpit\Teams-Auto-Joiner-master\auto_joiner.py", line 689, in <module>
    main()
  File "C:\Users\zodia\OneDrive\Pulpit\Teams-Auto-Joiner-master\auto_joiner.py", line 552, in main
    init_browser()
  File "C:\Users\zodia\OneDrive\Pulpit\Teams-Auto-Joiner-master\auto_joiner.py", line 177, in init_browser
    browser = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "C:\Users\zodia\AppData\Roaming\Python\Python39\site-packages\webdriver_manager\chrome.py", line 34, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\zodia\AppData\Roaming\Python\Python39\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
    binary_path = self.driver_cache.find_driver(browser_version, driver_name, os_type,
  File "C:\Users\zodia\AppData\Roaming\Python\Python39\site-packages\webdriver_manager\driver_cache.py", line 66, in find_driver
    metadata = self.get_metadata()
  File "C:\Users\zodia\AppData\Roaming\Python\Python39\site-packages\webdriver_manager\driver_cache.py", line 91, in get_metadata
    return json.load(outfile)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dam2452** [comment]
I also uninstalled and installed Google Chrome and tried to run the bot on the edge and then the same.

**Comment by dam2452** [comment]
Do you have any ideas, or any other advice?

**Comment by TobiasPankner** [comment]
Download Chromedriver from [here](https://chromedriver.chromium.org/downloads) (make sure it's the same version as Chrome).  
Then replace [Line 177](https://github.com/TobiasPankner/Teams-Auto-Joiner/blob/784a5f13f350888a5f97a1ee70f0a865a6b193a7/auto_joiner.py#L177) and [Line 179](https://github.com/TobiasPankner/Teams-Auto-Joiner/blob/784a5f13f350888a5f97a1ee70f0a865a6b193a7/auto_joiner.py#L179) with this code:  
`browser = webdriver.Chrome(executable_path=r"C:\path\to\chromedriver.exe",  options=chrome_options)` where path to chromedriver is the path you downloaded the chromedriver to.

**Comment by TobiasPankner** [comment]
Another thing you can try before that is put the bot outside of OneDrive, that might be causing issues.

**Comment by dam2452** [comment]
It's working now thanks for help.
